name: build

on:
  push:
    branches:
      - 'main'
  pull_request:

jobs:
  golangci-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: 'stable'
          cache: true
      - uses: golangci/golangci-lint-action@v6
  build:
    strategy:
      matrix:
        os: [ ubuntu-latest, macos-latest, windows-latest ]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: 'stable'
          cache: true
      - run: go run _examples/main.go || true
      - run: go test -v -failfast -race -coverpkg=./... -covermode=atomic -coverprofile=coverage.txt